services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app # Mount frontend code
      - /app/node_modules # Keep container's node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Ensure hot reload works
    profiles:
      - dev # Only run in development

  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=bitnami_myapp
    volumes:
      - mariadb_data:/bitnami/mariadb

  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  laravel-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    container_name: laravel-app
    depends_on:
      - mariadb
      - redis
    ports:
      - "8000:8000"
    # depends_on:
    #   mariadb:
    #     condition: service_healthy
    #   redis:
    #     condition: service_started
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=bitnami_myapp
      - DB_USERNAME=bn_myapp
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend:/app
      # Mount the public storage directory directly into the web root to avoid symlink issues with PHP's built-in server
      - ./backend/storage/app/public:/app/public/storage
    command: sh -c "
      until nc -z mariadb 3306; do
      echo 'Waiting for MariaDB...';
      sleep 2;
      done &&
      php artisan config:cache &&
      php artisan migrate --force &&
      php artisan serve --host=0.0.0.0 --port=8000"

volumes:
  mariadb_data:
