services:
  laravel-app:
    build:
      target: prod
    ports: []
    command: >
      sh -c "
        until nc -z mariadb 3306; do
          echo 'Waiting for MariaDB...';
          sleep 2;
        done &&
        php artisan migrate --force &&
        php-fpm -F
      "
  web:
    image: nginx:latest # <--- the Nginx image
    container_name: nginx
    ports:
      - "80:80" # expose HTTP to the host
      - "443:443" # if you want HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d # your Nginx configs
      - ./backend:/app # mount Laravel app
      - ./backend/public:/app/public # ensure Nginx can access public folder
    depends_on:
      - laravel-app
    restart: always
