networks:
  laravel-network:
    driver: bridge

services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app # Mount frontend code
      - /app/node_modules # Keep container's node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Ensure hot reload works

  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - laravel-network
    volumes:
      - mariadb_data:/bitnami/mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:
      - laravel-network

  laravel-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - laravel-network
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=bitnami_myapp
      - DB_USERNAME=bn_myapp
      - DB_PASSWORD=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend:/app
      # Mount the public storage directory directly into the web root to avoid symlink issues with PHP's built-in server
      - ./backend/storage/app/public:/app/public/storage
    command: sh -c "
      php artisan config:cache &&
      php artisan migrate --force &&
      php artisan serve --host=0.0.0.0 --port=8000"

volumes:
  mariadb_data:
